version: '3.2'
services:
  hatify:
    build: 
      context: hatify
      cache_from:
        - hugosandelius/hugosandelius.se:hatify
  tagga:
    build: 
      context: tagga
      cache_from:
        - hugosandelius/hugosandelius.se:tagga
  nginx:  
    build: 
      context: nginx
      cache_from:
        - hugosandelius/hugosandelius.se:nginx